tier1:
  wal: true
  path: /home/gsd/ruben/kvs-pmem/kvstore
  engine: pmdk
  policy: 
    type: performance
    levels: [0,1,2]
  cache_size: 75161927680
  disk_size: 32212254720

# tier2:
#   path: /home/gsd/ruben/kvs-nvme/kvstore
#   engine: posix
#   policy: 
#     type: capacity
#     threshold: 21474836480
#   cache_size: 21474836480
#   disk_size: 858993459200

# tier2:
#   path: /home/gsd/ruben/kvs-nvme/kvstore
#   engine: posix
#   policy: 
#     type: capacity
#     threshold: 2147483648
#   cache_size: 107374182400
#   disk_size: 644245094400


tier2:
  path: /home/gsd/ruben/kvs-nvme/kvstore
  engine: posix
  policy: 
    type: capacity
    threshold: 0
  cache_size: 52613349376
  disk_size: 161061273600

tier3:
  path: /home/gsd/ruben/kvs-sata/kvstore
  engine: posix
  policy: 
    type: capacity
    threshold: 2147483648
  cache_size: 107374182400
  disk_size: 858993459200


configs:
  redirection_map_file: "/home/gsd/ruben/kvs-nvme/kvstore/redirection_map.txt"
  file_extension: ".sst"
  profiler_log: "/home/gsd/ruben/kvs-nvme/log_profiler_3000.txt"
  activate_cache: "false"